### ISSUE TITLE
Missing "start" script

### ISSUE THREAD

**Issue by podlesny-j** [mschile/cypress-test-tiny#1]
<img width="590" alt="image" src="https://user-images.githubusercontent.com/78863563/220434326-4e2cae26-8d8a-4c69-b4fa-c1e7dfd0a7bb.png">

Hi, I'm having similar issues as described in https://github.com/cypress-io/cypress/issues/25718 so I thought I'd try to replicate this on your example repo, but the proclaimed "start" script is not defined in package.json and I am unfortunately too inexperienced to figure it out myself 😅

**Comment by podlesny-j** [comment]
also too noob to checkout the correct branch obviously.
sorry 🤐

**Comment by elihcsm** [comment]
No problem, I've missed checking out the correct branch numerous times and I've been doing this for years!
